baseURL: "https://victorbogo.me"
languageCode: "en-us"
title: "Victor Bogo"
theme: hugo-profile

Paginate: 3
googleAnalytics: G-YBX1L97WF2

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: https://world.hey.com/victorbogo
      weight: 1

params:
  color:
    darkmode:
      textColor: "#808080"
      #secondaryTextColor: "#ff0000"
      #backgroundColor: "#ff0000"
      #secondaryBackgroundColor: "#ff0000"
      #primaryColor: "#ff0000"
      #secondaryColor: "#ff0000"

  title: "Victor Bogo"
  description: Bogo's personal website
  useBootstrapCDN: false
  theme:
    disableThemeToggle: false
  navbar:
    disableSearch: true

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Victor Bogo."
    subtitle: "I am a continuous learning Site Reliability Engineer"
    content: "I once read that \"Hope is not a strategy\" and since then I try to use tools and processes to improve reliability outcomes"
    image: /images/photo2.jpeg
    button:
      download: false
      enable: true
      name: "About"
      url: "#about"
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/B0go
        - icon: fab fa-twitter
          url: https://twitter.com/victorbogo

  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/photo1.jpeg"
    content: |-
        Working as a Software Engineer in the first years of my career made me get in touch with interesting tools and platforms such as AWS, Docker, Kubernetes and Prometheus. After some time, I started to realize that the Site Reliability Engineering responsibilities and practices were something that I would really appreciate to work with.

    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "Terraform"
        - "Amazon Web Services"
        - "Golang"
        - "Kubernetes"
        - "Prometheus"
        - "Thanos"
        - "Docker"
        - "OpenTelemetry"
        - "EFK logs stack"
        - "PostgreSQL"

  # Experience
  experience:
    enable: true
    index: false
    items:
      - title: "Site Reliability Engineer"
        company:
          name: "37signals (Basecamp & Hey)"
          url: "https://37signals.com"
        date: "2022-present"
        content: |
          37signals is the company behind the well-known Basecamp and, more recently, Hey e-mail. It has been at the forefront of software development and remote work culture for decades and has chosen to be profitable since the 90s. Responsible for the conception of Ruby on Rails and other open-source tools, 37signals shared a lot with the community and continues to be one of the organizations that provoke changes in the industry.

          Projects:
          - Scale Prometheus monitoring in the cloud by running Thanos and its components
          - Revamp Prometheus on-prem monitoring by recreating the whole setup
      - title: "Senior Site Reliability Engineer"
        company:
          name: "Intricately Data"
          url: "https://intricately.com"
        date: "2022-2022"
        content: |
          Intricately is a data company based in the US that provides go-to-market technical information for anyone who sells products to tech companies. After a few weeks in Intricately, it got sold to HG Insights, a company in the same market.

          Projects:
          - Build terraform modules for AWS Backup and Vault monitoring
          - Evaluate possible solutions for migrating an on-VM MongoDB to a managed solution
          - Tackle security tasks reported by a third-party organization
      - title: "Senior Site Reliability Engineer"
        company:
          name: "QuintoAndar Real Estate"
          url: "https://www.quintoandar.com.br"
        date: "2021-2022"
        content: |
          QuintoAndar is an online real estate services company similar to Airbnb but for the long term. It is the second largest startup in LatAm, just behind Nubank. It has around 300 micro-services and more than 700 Kubernetes nodes in total. It has a big SRE team (approximately 70), and I was part of the observability-focused team.

          Projects:
           - Maintain all Prometheus instances used as the primary monitoring system. Each instance ran on top of Kubernetes and had more than 4TB of data on disk.
           - Install and configure Thanos to scale Prometheus monitoring through a lot of different Kubernetes clusters and improve how efficiently we could store monitoring data for the long-term
      - title: "Site Reliability Engineer"
        company:
          name: "Pier Insurtech"
          url: "https://pier.digital"
        date: "2020-2021"
        content: |
          Pier is the first Brazilian Insurtech, trying to solve the problem related to the bureaucracy and lack of high granularity data-driven decision making in the insurance world. At Pier, we needed to start structuring the DevOps/SRE culture from scratch, bringing some useful practices and tools to the table like post mortems, incident response, key engineering metrics like MTTD, MTTR, success rate and latency.

          Projects:
          - Start monitoring apps using Newrelic APM
          - Build the logging stack using ElasticSearch, FluentD and Kibana
          - Define the logging pattern
          - Organize PostgreSQL replicas, users and overall maintenance
          - Secure AWS account and IAM related configuration
      - title: "Site Reliability Engineer"
        company:
          name: "ContaAzul Software"
          url: "https://contaazul.com"
        date: "2018 - 2020"
        content: |
          As ContaAzul's platform is cloud based, all our customers access the same production environment and the number of customers is always growing we need to understand and apply some important concepts and practices in order to improve our overall service reliability. Besides being responsible for our cloud infrastructure, the SRE team is always looking into keeping the DevOps culture warm.

          Some of this practices are:

          - Post Mortems, to keep learning from failure
          - Automation, to scale and keep things consistent
          - SLIs, SLOs and SLAs, to build a contract between our product and development teams seeking balance
          - Release Engineering, to guarantee that changes to the production environment have a controlled impact
          - Monitoring, to enable true understanding of what is happening in production

          We currently own a self-managed Kubernetes cluster deployed to AWS responsible for running different kinds of application containers (microservices, jobs etc) and our data is mainly saved on PostgreSQL instances and S3

          Tech: Kubernetes, Docker, Prometheus, AWS, Grafana, Opentracing, Jaeger, Java
      - title: "Software Engineer"
        company:
          name: "ContaAzul Software"
          url: "https://contaazul.com"
        date: "2015 - 2018"
        content: |
          Team: Billing & Payments

          Our goal is to allow any customer using ContaAzul to exchange money through our platform.
          At ContaAzul, we have a lot of specific strategies related to payments. As no available platform met our requirements we opted to build and maintain our own payments infrastructure from the UIs that allow our customers to choose and pay using their preferred payment methods to the back-end that securely calculates things like subscriptions, recharge and discounts.

          We have some core values respected and followed by everyone in the team:

           - Quality
           - Reliability
           - Testability
           - Software engineering principles

          Our back-end microservices are mainly in Java (SprintBoot) and our front-end uses AngularJS with Material Design.
      - title: "Software Engineer"
        company:
          name: "Softexpert Software"
          url: "https://www.softexpert.com"
        date: "2013 - 2015"
        content: |
          Specific artifact development using web technologies (HTML, JavaScript, Ext, Ajax) with Object Oriented PHP and Java back-end connected to MS SQL Server, Oracle and Postgres. Java development environment configuration with Apache Ant, Maven and Tomcat. iReport report creation and maintenance.
      - title: "Infrastructure Intern"
        company:
          name: "Opentech Risk Management"
          url: "https://opentechgr.com.br"
        date: "2012 - 2013"
        content: |
          Solved hardware and software day-to-day problems. General computer maintenance (computer parts replacement, cleaning and saving). Installation and configuration of new work environments (Formatting, program installation and initial configuration). Monitoring of automated IT processes.

  # Achievements
  achievements:
    enable: true
    items:
      - title: CNCF Certified Kubernetes Administrator (CKA)
        content: I achieved in 2021 the Certified Kubernetes Administrator (CKA) certification.
        url: https://www.credly.com/badges/cb65f8d7-a8d4-44a8-85b0-a73aba85e974
      - title: AWS Solutions Architect - Associate
        content: I achieved in 2020 the AWS Solutions Architect Associate certification.
        url: https://www.credly.com/badges/bfd32d36-2023-4f1a-8e75-7efb4652e747
      - title: Oracle Certified Associate, Java SE 8 Programmer
        content: I achieved in 2015 the Oracle Certified Associate, Java SE 8 Programmer certification.
        url: "https://github.com/gurusabarish/hugo-profile"

  # projects
  projects:
    enable: false
    items:
      - title: Hugo Profile
        content: A highly customizable and mobile first Hugo template for personal portfolio and blog.
        image: /images/projects/profile.png
        # badges:
        #   - "Hugo"
        #   - "Bootstrap"
        #   - "Javascript"
        links:
          - icon: fa fa-envelope
            url: mailto:?subject=Hugo%20Profile%20Template&body=Check%20it%20out:%20https%3a%2f%2fhugo-profile.netlify.app%2fblog%2fmarkdown-syntax%2f
          - icon: fab fa-github
            url: https://github.com/gurusabarish/hugo-profile
          - icon: fab fa-twitter
            url: https://twitter.com/intent/tweet?text=Check+it+out:&url=https%3A%2F%2Fgithub.com%2Fgurusabarish%2Fhugo-profile

      - title: Image Converter
        content: A web app to convert image to pdf, png to jpg, png to jpg and png to webp without database using django.
        image: /images/projects/converter.jpg
        featured:
          name: Demo
          link: https://django-converter.herokuapp.com
        # badges:
        #   - "Django"
        #   - "Bootstrap"
        links:
          - icon: fab fa-github
            url: https://github.com/gurusabarish/converter

      - title: Hugo Profile V2
        content: A clean and simple Hugo template for personal portfolio and blog.
        image: /images/projects/profile2.jpg
        featured:
          name: Demo V2
          link: https://hugo-profile-2.netlify.app
        # badges:
        #   - "Hugo"
        #   - "Bootstrap"
        #   - "Javascript"
        links:
          - icon: fab fa-github
            url: https://github.com/gurusabarish/HugoProfileV2

  #Contact
  contact:
    enable: true
    content: Feel free to reach me out whenever you have any doubts or topics to discuss :)
    email: root@victorbogo.me
    btnName: Mail me

  footer:
    socialNetworks:
      github: https://github.com/B0go
      linkedin: https://www.linkedin.com/in/victorbogo/
      twitter: https://twitter.com/victorbogo
      instagram: https://www.instagram.com/victorbogo/
